const cfg=window.FIERA_CONFIG,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let state={dates:[],pavilions:[],people:[],availability:[],assignments:[],requirements:[]};let selectedDate=null;
const fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function modal(html){$('#modal').innerHTML=html;$('#modalBack').classList.add('show')} $('#modalBack').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.classList.remove('show')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#loginMsg').innerHTML=error?`<div class="notice danger">${esc(error.message)}</div>`:''}; $('#logout').onclick=()=>sb.auth.signOut();
sb.auth.onAuthStateChange((_e,session)=>setAuth(session)); async function setAuth(session){$('#loginView').style.display=session?'none':'block';$('#appView').style.display=session?'block':'none';if(session){$('#adminEmail').textContent=session.user.email;await loadAll()}}
$$('#nav button').forEach(b=>b.onclick=()=>{$$('#nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab));renderAll()});
async function loadAll(){const [d,p,pe,av,as,r]=await Promise.all([sb.from('event_dates').select('*').order('event_date'),sb.from('pavilions').select('*').order('sort_order'),sb.from('people').select('*').order('full_name'),sb.from('availability').select('*'),sb.from('assignments').select('*,people(full_name,phone),pavilions(name),event_dates(event_date)'),sb.from('requirements').select('*')]);
 const bad=[d,p,pe,av,as,r].find(x=>x.error);if(bad){toast(bad.error.message);return}state={dates:d.data,pavilions:p.data,people:pe.data,availability:av.data,assignments:as.data,requirements:r.data};if(!selectedDate)selectedDate=state.dates.find(x=>x.active)?.id||state.dates[0]?.id;renderAll()}
function renderAll(){renderOverview();renderNights();renderAvailability();renderPeople();renderSettings()}
function renderOverview(){const active=state.dates.filter(x=>x.active),conf=state.assignments.filter(x=>x.confirmation_status==='Confermato').length,pending=state.assignments.filter(x=>!x.confirmation_status||x.confirmation_status==='Da confermare').length,declined=state.assignments.filter(x=>x.confirmation_status==='Non posso').length;
 $('#overview').innerHTML=`<div class="card hero"><h1>Fiera sotto controllo.</h1><p>${active.length} serate configurate · ${state.people.length} persone registrate</p></div><div class="grid grid4 section"><div class="card kpi"><div class="num">${state.people.length}</div><div class="label">Persone</div></div><div class="card kpi"><div class="num">${state.assignments.length}</div><div class="label">Assegnazioni</div></div><div class="card kpi"><div class="num">${conf}</div><div class="label">Confermati</div></div><div class="card kpi"><div class="num">${pending+declined}</div><div class="label">Da gestire</div></div></div><div class="card section"><h2 class="section-title">Stato serate</h2><div class="grid grid2">${active.map(d=>nightSummary(d)).join('')}</div></div>`}
function nightSummary(d){const ass=state.assignments.filter(a=>a.date_id===d.id&&a.confirmation_status!=='Non posso').length;const req=state.requirements.filter(r=>r.date_id===d.id).reduce((s,r)=>s+(r.required_count||0),0);const ok=req&&ass>=req;return `<div class="date-card"><div class="date-head"><div class="date-title">${fmt(d.event_date)}</div><span class="status ${ok?'s-green':req?'s-orange':'s-gray'}">${req?ass+'/'+req:'Fabbisogno da impostare'}</span></div></div>`}
function renderNights(){const active=state.dates.filter(x=>x.active);if(!active.length){$('#nights').innerHTML='<div class="card empty">Aggiungi almeno una data nelle Impostazioni.</div>';return}if(!active.some(x=>x.id===selectedDate))selectedDate=active[0].id;const date=active.find(x=>x.id===selectedDate);
 const avIds=new Set(state.availability.filter(a=>a.date_id===selectedDate).map(a=>a.person_id));const assignedIds=new Set(state.assignments.filter(a=>a.date_id===selectedDate).map(a=>a.person_id));const available=state.people.filter(p=>avIds.has(p.id)&&!assignedIds.has(p.id));
 $('#nights').innerHTML=`<div class="pillbar">${active.map(d=>`<button class="pill ${d.id===selectedDate?'active':''}" data-date="${d.id}">${fmt(d.event_date)}</button>`).join('')}</div><div class="card section"><div class="date-head"><div><h2 class="section-title" style="margin:0">${fmt(date.event_date)}</h2><div class="muted">Padiglioni e copertura</div></div><button class="btn btn-primary" id="addAssignment">+ Assegna persona</button></div><div class="grid grid3 section">${state.pavilions.filter(p=>p.active).map(p=>pavilionCard(p)).join('')}</div></div><div class="card section"><h2 class="section-title">Disponibili non assegnati <span class="status s-gray">${available.length}</span></h2>${available.length?available.map(p=>availablePerson(p)).join(''):'<div class="empty">Nessuna persona ancora disponibile da assegnare.</div>'}</div>`;
 $$('#nights [data-date]').forEach(b=>b.onclick=()=>{selectedDate=Number(b.dataset.date);renderNights()});$('#addAssignment').onclick=()=>openAssign();$$('[data-quickassign]').forEach(b=>b.onclick=()=>openAssign(Number(b.dataset.quickassign)));$$('[data-wa]').forEach(b=>b.onclick=()=>openWhatsApp(Number(b.dataset.wa)));$$('[data-delassign]').forEach(b=>b.onclick=()=>deleteAssignment(Number(b.dataset.delassign)))}
function pavilionCard(p){const reqs=state.requirements.filter(r=>r.date_id===selectedDate&&r.pavilion_id===p.id);const req=reqs.reduce((s,r)=>s+(r.required_count||0),0);const ass=state.assignments.filter(a=>a.date_id===selectedDate&&a.pavilion_id===p.id&&a.confirmation_status!=='Non posso');const pct=req?Math.min(100,Math.round(ass.length/req*100)):0;return `<div class="pavilion"><div class="date-head"><h3>${esc(p.name)}</h3><span class="status ${req?(ass.length>=req?'s-green':'s-orange'):'s-gray'}">${req?ass.length+'/'+req:ass.length+' assegnati'}</span></div><div class="tiny muted">${esc(p.responsibles||'Responsabili da definire')}</div>${req?`<div class="progress ${ass.length<req?'warn':''}"><span style="width:${pct}%"></span></div>`:''}<div class="section">${ass.map(a=>`<div class="person"><div class="person-main"><div class="person-name">${esc(a.people?.full_name)}</div><div class="person-meta">${esc(a.role)} · ${esc(a.confirmation_status||'Da confermare')}</div></div><div class="button-row"><button class="btn btn-secondary" data-wa="${a.id}">WhatsApp</button><button class="btn btn-danger" data-delassign="${a.id}">×</button></div></div>`).join('')||'<div class="tiny muted">Nessuna assegnazione</div>'}</div></div>`}
function availablePerson(p){const a=state.availability.find(x=>x.date_id===selectedDate&&x.person_id===p.id);return `<div class="person"><div class="person-main"><div class="person-name">${esc(p.full_name)}</div><div class="person-meta">${esc(a?.role_preference||'Entrambi')} ${p.group_name?'· '+esc(p.group_name):''}</div></div><button class="btn btn-primary" data-quickassign="${p.id}">Assegna</button></div>`}
function openAssign(personId){const avPeople=state.people.filter(p=>state.availability.some(a=>a.date_id===selectedDate&&a.person_id===p.id));modal(`<h2 class="section-title">Nuova assegnazione</h2><div class="field"><label>Persona</label><select class="select" id="mPerson">${avPeople.map(p=>`<option value="${p.id}" ${p.id===personId?'selected':''}>${esc(p.full_name)}</option>`).join('')}</select></div><div class="field section"><label>Padiglione</label><select class="select" id="mPavilion">${state.pavilions.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field section"><label>Ruolo</label><select class="select" id="mRole"><option>Cucina</option><option>Servizio</option><option>Responsabile</option><option>Brace</option><option>Capo pizzaiolo</option><option>Altro</option></select></div><button class="btn btn-primary btn-block section" id="mSave">Assegna</button>`);$('#mSave').onclick=async()=>{const payload={date_id:selectedDate,person_id:Number($('#mPerson').value),pavilion_id:Number($('#mPavilion').value),role:$('#mRole').value,confirmation_status:'Da confermare'};const {error}=await sb.from('assignments').insert(payload);if(error)toast(error.message);else{$('#modalBack').classList.remove('show');toast('Assegnazione salvata');await loadAll()}}}
async function deleteAssignment(id){if(!confirm('Rimuovere questa assegnazione?'))return;const {error}=await sb.from('assignments').delete().eq('id',id);if(error)toast(error.message);else await loadAll()}
function openWhatsApp(id){const a=state.assignments.find(x=>x.id===id);if(!a)return;const base=location.href.replace(/admin\.html.*$/,'confirm.html');const link=`${base}?t=${a.confirmation_token}`;const phone=(a.people?.phone||'').replace(/\D/g,'');const text=`Ciao ${a.people?.full_name||''}, ti ricordiamo il servizio alla Fiera:\n\n📅 ${fmt(a.event_dates?.event_date)}\n📍 ${a.pavilions?.name}\n👤 ${a.role}\n\nConferma qui la tua presenza:\n${link}`;window.open(`https://wa.me/${phone.startsWith('39')?phone:'39'+phone}?text=${encodeURIComponent(text)}`,'_blank')}
function renderAvailability(){const rows=state.availability.map(a=>{const p=state.people.find(x=>x.id===a.person_id),d=state.dates.find(x=>x.id===a.date_id);return `<tr><td>${esc(p?.full_name)}</td><td>${d?fmt(d.event_date):''}</td><td>${esc(a.role_preference)}</td><td>${esc(p?.group_name||'')}</td></tr>`}).join('');$('#availability').innerHTML=`<div class="card"><h2 class="section-title">Tutte le disponibilità</h2><div class="table-wrap"><table><thead><tr><th>Persona</th><th>Serata</th><th>Disponibile per</th><th>Gruppo</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Nessun dato</td></tr>'}</tbody></table></div></div>`}
function renderPeople(){ $('#people').innerHTML=`<div class="card"><h2 class="section-title">Persone</h2>${state.people.map(p=>`<div class="person"><div><div class="person-name">${esc(p.full_name)}</div><div class="person-meta">${esc(p.phone)} ${p.group_name?'· '+esc(p.group_name):''}</div></div></div>`).join('')||'<div class="empty">Nessuna persona registrata.</div>'}</div>`}
function renderSettings(){const dateRows=state.dates.map(d=>`<div class="person"><div><div class="person-name">${fmt(d.event_date)}</div><div class="person-meta">${d.active?'Attiva':'Disattivata'}</div></div><div class="button-row"><button class="btn btn-secondary" data-toggle-date="${d.id}">${d.active?'Disattiva':'Attiva'}</button><button class="btn btn-danger" data-delete-date="${d.id}">Elimina</button></div></div>`).join('');
 $('#settings').innerHTML=`<div class="grid grid2"><div class="card"><div class="date-head"><h2 class="section-title">Date Fiera</h2><button class="btn btn-primary" id="newDate">+ Data</button></div>${dateRows||'<div class="empty">Nessuna data</div>'}</div><div class="card"><h2 class="section-title">Padiglioni</h2>${state.pavilions.map(p=>`<div class="person"><div><div class="person-name">${esc(p.name)}</div><div class="person-meta">${esc(p.responsibles||'')}</div></div><button class="btn btn-secondary" data-edit-pav="${p.id}">Modifica</button></div>`).join('')}</div></div><div class="card section"><h2 class="section-title">Fabbisogni</h2><p class="muted">Imposta quante persone servono per data, padiglione e ruolo.</p><button class="btn btn-primary" id="newReq">+ Aggiungi fabbisogno</button><div class="table-wrap section"><table><thead><tr><th>Data</th><th>Padiglione</th><th>Ruolo</th><th>N.</th><th></th></tr></thead><tbody>${state.requirements.map(r=>{const d=state.dates.find(x=>x.id===r.date_id),p=state.pavilions.find(x=>x.id===r.pavilion_id);return `<tr><td>${d?fmt(d.event_date):''}</td><td>${esc(p?.name)}</td><td>${esc(r.role)}</td><td>${r.required_count}</td><td><button class="btn btn-danger" data-delreq="${r.id}">×</button></td></tr>`}).join('')}</tbody></table></div></div>`;
 $('#newDate').onclick=()=>modal(`<h2 class="section-title">Aggiungi serata</h2><div class="field"><label>Data</label><input class="input" type="date" id="dateInput"></div><div class="field section"><label>Etichetta facoltativa</label><input class="input" id="dateLabel" placeholder="Es. Apertura"></div><button class="btn btn-primary btn-block section" id="saveDate">Salva</button>`);setTimeout(()=>{const b=$('#saveDate');if(b)b.onclick=saveDate},0);
 $$('[data-toggle-date]').forEach(b=>b.onclick=()=>toggleDate(Number(b.dataset.toggleDate)));$$('[data-delete-date]').forEach(b=>b.onclick=()=>deleteDate(Number(b.dataset.deleteDate)));$$('[data-edit-pav]').forEach(b=>b.onclick=()=>editPav(Number(b.dataset.editPav)));$('#newReq').onclick=openReq;$$('[data-delreq]').forEach(b=>b.onclick=()=>deleteReq(Number(b.dataset.delreq)))}
async function saveDate(){const {error}=await sb.from('event_dates').insert({event_date:$('#dateInput').value,label:$('#dateLabel').value,active:true});if(error)toast(error.message);else{$('#modalBack').classList.remove('show');await loadAll()}}
async function toggleDate(id){const d=state.dates.find(x=>x.id===id);await sb.from('event_dates').update({active:!d.active}).eq('id',id);await loadAll()} async function deleteDate(id){if(confirm('Eliminare la data e i dati collegati?')){const {error}=await sb.from('event_dates').delete().eq('id',id);if(error)toast(error.message);else await loadAll()}}
function editPav(id){const p=state.pavilions.find(x=>x.id===id);modal(`<h2 class="section-title">${esc(p.name)}</h2><div class="field"><label>Responsabili / riferimenti</label><textarea id="pResp" rows="5">${esc(p.responsibles||'')}</textarea></div><div class="field section"><label>Note</label><textarea id="pNotes" rows="3">${esc(p.notes||'')}</textarea></div><button class="btn btn-primary btn-block section" id="savePav">Salva</button>`);$('#savePav').onclick=async()=>{await sb.from('pavilions').update({responsibles:$('#pResp').value,notes:$('#pNotes').value}).eq('id',id);$('#modalBack').classList.remove('show');await loadAll()}}
function openReq(){modal(`<h2 class="section-title">Nuovo fabbisogno</h2><div class="field"><label>Data</label><select class="select" id="rDate">${state.dates.filter(d=>d.active).map(d=>`<option value="${d.id}">${fmt(d.event_date)}</option>`).join('')}</select></div><div class="field section"><label>Padiglione</label><select class="select" id="rPav">${state.pavilions.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field section"><label>Ruolo</label><select class="select" id="rRole"><option>Cucina</option><option>Servizio</option><option>Responsabile</option><option>Brace</option><option>Capo pizzaiolo</option><option>Altro</option></select></div><div class="field section"><label>Persone necessarie</label><input class="input" type="number" min="0" id="rCount" value="1"></div><button class="btn btn-primary btn-block section" id="saveReq">Salva</button>`);$('#saveReq').onclick=async()=>{const {error}=await sb.from('requirements').upsert({date_id:Number($('#rDate').value),pavilion_id:Number($('#rPav').value),role:$('#rRole').value,required_count:Number($('#rCount').value)},{onConflict:'date_id,pavilion_id,role'});if(error)toast(error.message);else{$('#modalBack').classList.remove('show');await loadAll()}}}
async function deleteReq(id){await sb.from('requirements').delete().eq('id',id);await loadAll()}
(async()=>{const {data:{session}}=await sb.auth.getSession();setAuth(session)})();
