const cfg=window.FIERA_CONFIG||{};const $=s=>document.querySelector(s);const sb=(window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY)?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;let eventDates=[];const selections={};
const fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'));
const shortFmt=d=>new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
function notice(t,type='info'){const el=$('#message');el.innerHTML=`<div class="inline-notice ${type}">${t}</div>`}
function updateCount(){const n=Object.keys(selections).length;$('#dateCount').textContent=n;$('#dateCount').classList.toggle('active',n>0)}
function renderDates(){const wrap=$('#dates');wrap.innerHTML='';if(!eventDates.length){wrap.innerHTML='<div class="empty-state">Le date non sono ancora state configurate.</div>';return}eventDates.forEach(x=>{const row=document.createElement('article');row.className='availability-row';row.innerHTML=`<button type="button" class="date-toggle" aria-pressed="false"><span class="date-badge">${shortFmt(x.event_date)}</span><span class="date-copy"><strong>${fmt(x.event_date)}</strong>${x.label?`<small>${x.label}</small>`:''}</span><span class="checkmark">✓</span></button><div class="role-picker"><button type="button" data-role="Cucina">Cucina</button><button type="button" data-role="Servizio">Servizio</button><button type="button" data-role="Entrambi">Entrambi</button></div>`;const t=row.querySelector('.date-toggle'),picker=row.querySelector('.role-picker');t.onclick=()=>{const selected=row.classList.toggle('selected');t.setAttribute('aria-pressed',selected?'true':'false');if(selected){selections[x.id]='Entrambi';picker.querySelector('[data-role="Entrambi"]').classList.add('active')}else{delete selections[x.id];picker.querySelectorAll('button').forEach(b=>b.classList.remove('active'))}updateCount()};picker.querySelectorAll('button').forEach(b=>b.onclick=()=>{selections[x.id]=b.dataset.role;picker.querySelectorAll('button').forEach(z=>z.classList.toggle('active',z===b))});wrap.appendChild(row)});updateCount()}
async function loadConfig(){if(!sb){notice('Configurazione Supabase mancante o non valida.','danger');$('#dates').innerHTML='<div class="empty-state">Configurazione non disponibile.</div>';return}const {data,error}=await sb.rpc('public_fiera_config');if(error){notice('Impossibile caricare le date: '+error.message,'danger');return}document.title=(data?.name||cfg.APP_NAME||'Fiera')+' · Disponibilità';$('#brand').textContent=data?.name||cfg.APP_NAME||'Fiera Gastronomica';eventDates=(data?.dates||[]).filter(x=>x.active);renderDates()}
$('#availabilityForm').addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;if(!Object.keys(selections).length){notice('Seleziona almeno una serata.','danger');return}const btn=$('#submitBtn');btn.disabled=true;btn.textContent='Invio in corso…';const payload={p_full_name:$('#fullName').value.trim(),p_phone:$('#phone').value.trim(),p_group_name:$('#groupName').value.trim(),p_notes:$('#notes').value.trim(),p_availability:Object.entries(selections).map(([date_id,role])=>({date_id:Number(date_id),role}))};const {error}=await sb.rpc('submit_availability',payload);btn.disabled=false;btn.textContent='Invia disponibilità';if(error){notice('Errore: '+error.message,'danger');return}notice('Disponibilità salvata. Grazie!','success');document.querySelector('.primary-cta').scrollIntoView({behavior:'smooth',block:'center'})});
loadConfig();
