-- GESTIONE FIERA - schema Supabase
-- Esegui tutto questo file in Supabase > SQL Editor > New query > Run.

create extension if not exists pgcrypto;

create table if not exists public.event_dates (
  id bigint generated by default as identity primary key,
  event_date date not null unique,
  label text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.pavilions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  responsibles text,
  notes text,
  active boolean not null default true,
  sort_order int not null default 100
);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  group_name text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  date_id bigint not null references public.event_dates(id) on delete cascade,
  role_preference text not null check (role_preference in ('Cucina','Servizio','Entrambi')),
  created_at timestamptz not null default now(),
  unique(person_id,date_id)
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  date_id bigint not null references public.event_dates(id) on delete cascade,
  pavilion_id bigint not null references public.pavilions(id),
  role text not null,
  confirmation_status text not null default 'Da confermare' check (confirmation_status in ('Da confermare','Confermato','Non posso')),
  confirmation_token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now(),
  unique(person_id,date_id)
);

create table if not exists public.requirements (
  id bigint generated by default as identity primary key,
  date_id bigint not null references public.event_dates(id) on delete cascade,
  pavilion_id bigint not null references public.pavilions(id) on delete cascade,
  role text not null,
  required_count int not null default 0 check(required_count>=0),
  unique(date_id,pavilion_id,role)
);

-- Padiglioni e riferimenti 2026 ricavati dal file fiera_2026_servizi_per_padiglione_aggiornato.xlsm.
insert into public.pavilions(name,responsibles,notes,sort_order) values
('Ristorante','Anna Guidarini; Andrea Donati; Luca Piciarelli; Costanza Bartali; Eugenia/Gaia','Chi e al Ristorante non va assegnato altrove nella stessa serata.',10),
('Orto di Ottaviano','Galini Giovanni; Corti Valentina; Cresti Francesco; Margherita La Manna; Francesco Tanzini','2/3 persone alle 18:00 per aiuto cucina antipasti.',20),
('Osteria/Vinaio','Michele Rubini; Asia Nicolella; Costantino Pais; Stefania Bugnoli; Tommi Mancianti; Giulia Zeppi; Alessio Bertini','Quando c e Osteria i gruppi fanno da se.',30),
('Unto','Giada Pucci; Niccolo Scali; Martina Bugnoli; Simone Turchi; David Fabiani; Mattia Pallari','Cucina pasta/fritto e servizio banco/tavoli.',40),
('Pizzeria','Foffo; Sandro Pasqualetti; Alice Nocentini; Giulio La Manna','Capo pizzaiolo da gestire come ruolo separato.',50),
('Rustico - Cucina','Gepponi; Fattorini 1/2; Pisquillo; Samuele Carli; Sergio Pistolesi; Luca Bartoli; Panzer; Giovanni Griccioli','Sottodivisione del Rustico.',60),
('Rustico - Brace','Prope; Sembola; Capino; Marcello Salerno; Lenzini C.; Cambi M.; Fagioli Andrea; Bidone; Batano; Benedetto D''Angelo','Sottodivisione del Rustico.',61),
('Rustico - Qua e La','Sarina Parigi; Prestigi Roberta; Checco Vegni; Cerretani; Vessichelli A.; Andrea Radi; Elisa Baroni; Gabriele Cannoni; Sofia Lorenzini','Sottodivisione del Rustico.',62),
('Barrino','Francesca Carletti; Simone Burroni; Ginevra Semplici; Leonardo Pini; Sara Bonechi','2/3 responsabili a sera.',70),
('Birreria','Bernardo Rizzi; Giovanni Carli; Tommaso Pallari; Emma Sarri','2 responsabili a sera.',80),
('Gin','Matteo Cenni; Marco Scortecci; Giulio Manganelli; Simone Bagnolesi','2 responsabili a sera; servizio condiviso 7/8 persone.',90),
('Vini','Benedetta Cenni; Flaminia Piconi; Caterina Picchi; Jacopo Biancucci','2 responsabili a sera.',100),
('Bar','Cesare Bozzi; Giulio Fagioli; Niccolo Boscagli; Camilla Panerati; Cristina Cannoni','3/4 responsabili a sera, secondo weekend/discoteca.',110),
('Dolci','Brombin; Sabrina; Anna Bertini; Emilia Cheli; Morgana','2 responsabili a sera, massimo 3.',120),
('Barberi','Niccolo Innocenti; Alessandro Spaggiari; Giacomo Braccagni; Giulio Oretti','3 responsabili a sera.',130),
('La Baita',null,'Padiglione aggiunto. Responsabili da definire.',140)
on conflict(name) do update set responsibles=excluded.responsibles,notes=excluded.notes,sort_order=excluded.sort_order;

-- Date 2026 iniziali. Dall'admin puoi eliminarle, disattivarle o aggiungere quelle di ogni nuovo anno.
insert into public.event_dates(event_date,label,active) values
('2026-07-25',null,true),('2026-07-26',null,true),('2026-07-27',null,true),('2026-07-28',null,true),('2026-07-29',null,true),('2026-07-30',null,true),('2026-07-31',null,true),('2026-08-01',null,true),('2026-08-02',null,true),('2026-08-03',null,true),('2026-08-04',null,true),('2026-08-05',null,true)
on conflict(event_date) do nothing;

-- RLS: le tabelle restano private al pubblico. Gli utenti autenticati (admin) possono gestirle.
alter table public.event_dates enable row level security;
alter table public.pavilions enable row level security;
alter table public.people enable row level security;
alter table public.availability enable row level security;
alter table public.assignments enable row level security;
alter table public.requirements enable row level security;

do $$ begin
  create policy "admin event_dates" on public.event_dates for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "admin pavilions" on public.pavilions for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "admin people" on public.people for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "admin availability" on public.availability for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "admin assignments" on public.assignments for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "admin requirements" on public.requirements for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- Configurazione pubblica: espone soltanto nome app e date attive, non persone o turni.
create or replace function public.public_fiera_config()
returns jsonb language sql security definer set search_path=public as $$
  select jsonb_build_object(
    'name','Fiera Gastronomica',
    'dates',coalesce((select jsonb_agg(jsonb_build_object('id',id,'event_date',event_date,'label',label,'active',active) order by event_date) from public.event_dates where active), '[]'::jsonb)
  );
$$;
revoke all on function public.public_fiera_config() from public;
grant execute on function public.public_fiera_config() to anon, authenticated;

-- Il pubblico invia/aggiorna le proprie disponibilita senza poter leggere il database.
create or replace function public.submit_availability(p_full_name text,p_phone text,p_group_name text,p_notes text,p_availability jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_phone text; v_person bigint; item jsonb;
begin
  v_phone := regexp_replace(coalesce(p_phone,''),'[^0-9+]','','g');
  if length(v_phone)<7 then raise exception 'Numero di telefono non valido'; end if;
  if length(trim(coalesce(p_full_name,'')))<2 then raise exception 'Nome non valido'; end if;
  insert into public.people(full_name,phone,group_name,notes,updated_at)
  values(trim(p_full_name),v_phone,nullif(trim(p_group_name),''),nullif(trim(p_notes),''),now())
  on conflict(phone) do update set full_name=excluded.full_name,group_name=excluded.group_name,notes=excluded.notes,updated_at=now()
  returning id into v_person;
  delete from public.availability where person_id=v_person;
  for item in select * from jsonb_array_elements(coalesce(p_availability,'[]'::jsonb)) loop
    insert into public.availability(person_id,date_id,role_preference)
    values(v_person,(item->>'date_id')::bigint,item->>'role');
  end loop;
  return jsonb_build_object('ok',true,'person_id',v_person);
end $$;
revoke all on function public.submit_availability(text,text,text,text,jsonb) from public;
grant execute on function public.submit_availability(text,text,text,text,jsonb) to anon,authenticated;

-- Conferma pubblica tramite token casuale: espone solo il singolo servizio legato al token.
create or replace function public.get_confirmation(p_token uuid)
returns table(full_name text,event_date date,pavilion_name text,role text,confirmation_status text)
language sql security definer set search_path=public as $$
 select pe.full_name,d.event_date,p.name,a.role,a.confirmation_status
 from public.assignments a join public.people pe on pe.id=a.person_id join public.event_dates d on d.id=a.date_id join public.pavilions p on p.id=a.pavilion_id
 where a.confirmation_token=p_token limit 1;
$$;
revoke all on function public.get_confirmation(uuid) from public;
grant execute on function public.get_confirmation(uuid) to anon,authenticated;

create or replace function public.respond_confirmation(p_token uuid,p_status text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if p_status not in ('Confermato','Non posso') then raise exception 'Stato non valido'; end if;
 update public.assignments set confirmation_status=p_status where confirmation_token=p_token;
 return found;
end $$;
revoke all on function public.respond_confirmation(uuid,text) from public;
grant execute on function public.respond_confirmation(uuid,text) to anon,authenticated;
